### ISSUE TITLE
Not sure how to play 2 players

### ISSUE THREAD

**Issue by pathetix** [bui/taiko-web#110]
Don't really understand how to enable 2 player mode.
Are there any instructions?

**Comment by bui** [comment]
There is 2 ways:

* Select ネットプレイ using the options button when selecting a song, then, you will play against any other player who has netplay enabled for that song
* Click the white part at the bottom of the screen, and share the link with someone. You will then both control the song select and can continue playing after the song ends

**Comment by pathetix** [comment]
Oh thank you!! I didn't know there was a shareable link!
