### ISSUE TITLE
An error occurred, please refresh at 55-57%

### ISSUE THREAD

**Issue by capomic** [bui/taiko-web#126]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
![default](https://user-images.githubusercontent.com/39001397/51534078-b6ea5080-1e7f-11e9-8880-5db4f9e267d9.png)

Windows 10 Chrome/Firefox

**Comment by capomic** [comment]
[taiko.bui.pm-1548158521207.log](https://github.com/bui/taiko-web/files/2782654/taiko.bui.pm-1548158521207.log)

![image](https://user-images.githubusercontent.com/39001397/51534490-d766da80-1e80-11e9-86dd-ea61db98ccb6.png)

Is this what you are talking about?

**Comment by bui** [comment]
Yes, thank you. Please open some of the data.taiko.zone links, do you get an error?

**Comment by capomic** [comment]
I can actually download all the wav and font files, but there are still 403 errors in the console.
https://taiko.bui.pm/src/js/loader.js?71959da
This is a loader.js for one of the files that displays an error. I have already turned off my adblocker.

**Comment by capomic** [comment]
The preview tab is empty and response tab says 'This request has no response data available".
I was playing fine yesterday but it suddenly won't work for my computer.
I can load the game fine on phone, so there must be something wrong with my browser :(

**Comment by capomic** [comment]
Working again! Thanks

**Comment by Pickcrafter** [comment]
this will useally happen in schools
