### ISSUE TITLE
TJA not loaded correctly

### ISSUE THREAD

**Issue by rexx0520** [bui/taiko-web#131]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

This TJA file is not loaded correctly. Is there TJA functions not implemented?
TJA file is attached below.

[adrenaline!!!.zip](https://github.com/bui/taiko-web/files/2786694/adrenaline.zip)

**Comment by bui** [comment]
Can you please explain what you mean by "correctly"? I was able to load and play the song successfully. What is the problem?

**Comment by rexx0520** [comment]
> Can you please explain what you mean by "correctly"? I was able to load and play the song successfully. What is the problem?

https://www.youtube.com/watch?v=Zpj5pGZ49lE
The map should act as the video, mine didn't...

**Comment by bui** [comment]
I checked, and there are errors in the TJA file. Commands (eg. `#SCROLL`, `#MEASURE`) need to have a space character before the value to work correctly.

**Comment by rexx0520** [comment]
I see. Thanks.
