### ISSUE TITLE
Function for game to store game scores locally

### ISSUE THREAD

**Issue by bckps7336** [bui/taiko-web#134]
The game can utilize localStorage to store scores, and display icons in song selection menu.

**Comment by LoveEevee** [comment]
- The current method of counting how much points the player gets for each note is incorrect, the final score is way off from what you would get normally
- Gauge is very wrong, it is very easy to normal-clear songs, full combos are unaffected there
Storing wrong scores does not make sense to me, displaying silver crowns when the gauge is wrong does not make sense either. Storing golden crowns does make sense, but it would be tough for some people to get those
