### ISSUE TITLE
 Missing ";" from Database setup

### ISSUE THREAD

**Issue by OoERASERoO** [bui/taiko-web#135]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Missing ";" from Database setup

CREATE TABLE "song_skins" ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `name` TEXT NOT NULL, `song` TEXT, `stage` TEXT, `don` TEXT )

I
I
I
v

CREATE TABLE "song_skins" ( `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `name` TEXT NOT NULL, `song` TEXT, `stage` TEXT, `don` TEXT );

**Comment by bui** [comment]
Thanks!
