### ISSUE TITLE
No music for the uploaded song

### ISSUE THREAD

**Issue by HomoRetardus** [bui/taiko-web#147]
I tried to use the upload function to upload a few maps to the website, the files I uploaded contain both the OGG file and the TJA file, however after I uploaded the files, half of them do not have their background music, i can only hit the notes without the music after I started the song. The one I attached is one of them.

```
Taiko-Web version: https://github.com/bui/taiko-web/commit/7411022b14f108cb241c5771cb2aad6a88ac659c
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Screen size: 1536x754, outer: 1536x824, ratio: 1.25
Blur performance: 2ms, all images: 329ms
Page load: 1.8s
Language: en (en-US, en, zh-TW)
```
[koihacaosnoshimobenari.zip](https://github.com/bui/taiko-web/files/3102905/koihacaosnoshimobenari.zip)

**Comment by IzanLarumbe** [comment]
Transform the OGG file to Mp3 and it should work fine.
