### ISSUE TITLE
Gauge system and the browse function

### ISSUE THREAD

**Issue by speedymlg** [bui/taiko-web#157]
In the arcade version the clear target on oni mode is higher than the other difficulty but why in here dont? Also what does the "Browse" function do?
![image](https://user-images.githubusercontent.com/20207183/59838246-d4f9a580-9378-11e9-9c0d-65016118935a.png)

**Comment by tommycs127** [comment]
The "Browse" function is for you to open your .tja or .osu file and play.
But as far as I know, this function does not support online session.

**Comment by powwu** [comment]
@bui is aware of this issue, as shown by this screenshot:

![](https://raw.githubusercontent.com/powwu/the-dump/master/Selection_002.png)

**Comment by speedymlg** [comment]
Ah alright.
And also i would love to see 4+ player in a online session.

**Comment by bui** [comment]
Gauge has been fixed in #186
