### ISSUE TITLE
SSL Date Expired

### ISSUE THREAD

**Issue by wynn1212** [bui/taiko-web#159]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

SSL date expired on https://taiko.bui.pm/
![螢幕快照_2019-06-23_02-51-08](https://user-images.githubusercontent.com/10562889/59967781-c9b59e00-9561-11e9-992e-57eac2c63d85.png)

**Comment by bui** [comment]
fixed
