### ISSUE TITLE
Error message on ipad (chrome and safari)

### ISSUE THREAD

**Issue by s3781948** [bui/taiko-web#164]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
![FBCE481B-27FC-426A-A308-2A9BB582D28A](https://user-images.githubusercontent.com/48814176/63983158-da0d6a80-cb08-11e9-8ac1-3de815ca55a9.jpeg)

Error occurs on ipad (chrome and safari) after selecting difficulty. Tried clearing cache, changing resolution and language, still gives the error message
```
Taiko-Web version: https://github.com/purerosefallen/taiko-web-another/commit/028db66d9174256ff5ac66584ea062eaee6c0384

**Comment by bui** [comment]
taiko.moecube.com does not use this version of taiko-web. (the reason you are getting an error is because taiko.moecube.com uses OGG instead of MP3, the former of which is unsupported on iOS)
