### ISSUE TITLE
Request to add songs to regular list

### ISSUE THREAD

**Issue by Dangan2020** [bui/taiko-web#168]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Just asking something... is it possible to request the creator of the system to add other official charts?
If it does accept, then I'm requesting EkiBEN2000 and Hikari no Kanata e (Ex ver.)

**Comment by bui** [comment]
This is unrelated to taiko-web as a project.
