### ISSUE TITLE
ローディングから先に進まない

### ISSUE THREAD

**Issue by Hayao0819** [bui/taiko-web#169]
# 環境
OS : ArchLinux
Kernel : 4.19.78-2-lts
ブラウザ：Chromium77.0.3865.120
（Firefoxでは正常に起動しました）
M/B : GIGABYTE H61M-DS2
CPU : Xeon E3-1275
GPU : GTX1050Ti
RAM : DDR3 4GB x 2
SSD : 250GB

# 現象
以下の画面が出て先に勧めません 
![image](https://user-images.githubusercontent.com/32128205/66718618-603df180-edd5-11e9-8c02-47ecafaca210.png)

Consoleのスクショも載せておきます
![image](https://user-images.githubusercontent.com/32128205/66718644-a8f5aa80-edd5-11e9-8676-8d0527c8bdd5.png)
![image](https://user-images.githubusercontent.com/32128205/66718647-b0b54f00-edd5-11e9-955a-72279286d29a.png)

**Comment by bui** [comment]
ご報告ありがとうございます。 どのデスクトップ環境を使用していますか？

**Comment by Dangan2020** [comment]
Uh... I don't understand japanese...

Il giorno dom 13 ott 2019 alle 19:45 Bui <notifications@github.com> ha
scritto:

**Comment by Hayao0819** [comment]
Xfce4を使用しています。

```bash
$ pacman -Q | grep xfce4
libxfce4ui 4.14.1-2
libxfce4util 4.14.0-1
xfce4-appfinder 4.14.0-1
xfce4-notifyd 0.4.4-2
xfce4-panel 4.14.1-1
xfce4-power-manager 1.6.5-2
xfce4-pulseaudio-plugin 0.4.2-2
xfce4-screenshooter 1.9.6-1
xfce4-session 4.14.0-2
xfce4-settings 4.14.1-1
xfce4-terminal 0.8.8-2
xfce4-whiskermenu-plugin 2.3.3-1
```

**Comment by Hayao0819** [comment]
先程確認したところ同じ環境で正常に起動できました！
