### ISSUE TITLE
Allow Don & Ka to be Muted

### ISSUE THREAD

**Issue by Chi7519** [bui/taiko-web#182]
#﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

I would love the ability to mute the Don & Ka sounds. Right now, I have to turn the music volume up to 2 or more to drown out the noise. I sometimes play with Wireless earbuds, and while I can adjust latency, the Don & Ka still mess me up sometimes.

**Comment by LoveEevee** [comment]
Thanks for reporting, the option will be added when pr #176 is merged

**Comment by Chi7519** [comment]
Thank you so much!
