### ISSUE TITLE
Idea and song archive site.

### ISSUE THREAD

**Issue by jomin398** [bui/taiko-web#183]
###### Describe the problem you are 
Add vocaloid songs from here!
(And others too.
.)
[Online tja file archive( tested from tja mobile app)](https://taikosanjiro-humenroom.net/original/original-vocaloid/) << it wroten with Japanese, turn on auto translate.

And add folder view.
[Image 1](https://images.app.goo.gl/KmFTU3JFUHo4gGCs9) 
You can find that exmples from YouTube playthrough videos

**Comment by bui** [comment]
1. We don't accept song requests via this repository.
2. Quick category navigation has already been implemented instead of folders.
