### ISSUE TITLE
taiko.bui.pm website stuck at loading screen 72%

### ISSUE THREAD

**Issue by JoltP** [bui/taiko-web#192]
website wont work, stuck at 72%...
But it works with my phone.

![tbp](https://user-images.githubusercontent.com/25887588/76582884-92818580-6512-11ea-95b3-26141377eb37.png)

**Comment by bui** [comment]
Please check the JavaScript console for errors.

**Comment by JoltP** [comment]
not sure...

![image](https://user-images.githubusercontent.com/25887588/76583562-826aa580-6514-11ea-9abe-d03747719763.png)

**Comment by purerosefallen** [comment]
My fork also had this problem. There would be chances that the load would fail at around 60% or 70%. Let me double check the error later.

**Comment by BlueJYT** [comment]
Actually, I am on Chrome OS, and I had a problem similar where mine got stuck around 40% then said that there was an error. I just restarted my system and it fixed itself

**Comment by bui** [comment]
My suspicion is that this is just a network error/partial content download. Please correct me if I'm mistaken.

**Comment by BlueJYT** [comment]
@bui, It probably was, because I am able to play it with ease now.
