### ISSUE TITLE
Enable local chart imports on mobile devices

### ISSUE THREAD

**Issue by orenji4514** [bui/taiko-web#193]
######下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。

**Comment by bui** [comment]
https://caniuse.com/#feat=input-file-directory
現在は、モバイル端末では不可能です

**Comment by LoveEevee** [comment]
The functionality has been added in #273 using Google Drive, but it has not been enabled on taiko.bui.pm due to complications with Google's OAuth consent screen
