### ISSUE TITLE
Loading stuck at 37%

### ISSUE THREAD

**Issue by lambdagit101** [bui/taiko-web#196]
I cannot do anything after 37% is written on the loading bar. I can't give any information rather than this

**Comment by JoltP** [comment]
![image](https://user-images.githubusercontent.com/25887588/76754991-11e6b180-67be-11ea-9ee1-e3a294901be1.png)
 same here...

**Comment by cces1004406** [comment]
It seems the resource on https://ks1.kiremani.net/ were broken

**Comment by bui** [comment]
Should be back now
