### ISSUE TITLE
Loading stuck(again) at 48%

### ISSUE THREAD

**Issue by lambdagit101** [bui/taiko-web#201]
My loading is stuck at 48% for whatever reason
Last time was at 37%

**Comment by notthecreatoroftaikoforcelv5** [comment]
I'm having a similar problem.
Sometimes the songs (not the page) won't load. More stuff like this is happening too. Check the Issue for more information.

**Comment by bui** [comment]
I can't look into this without javascript error logs.

**Comment by lambdagit101** [comment]
Checked the Chrome console, no errors

**Comment by bui** [comment]
What about the network tab? Did any resources fail to load?

**Comment by lambdagit101** [comment]
Checked that too. Nothing failed

**Comment by notthecreatoroftaikoforcelv5** [comment]
Note: Wait for a while on the online session join page (maybe a minute) and
then quit and try netplaying. Not in the special options menu (song
options). Loading songs actually works, but its slower than usual (about 10
seconds average, now takes about 25-30 seconds.)

**Comment by purerosefallen** [comment]
Did `An error occurred, please refresh` appeared?

**Comment by LukewarmCat** [comment]
I have this issue when I don't have the Firefox/Chrome window open on loading. Keep it open.

**Comment by LukewarmCat** [comment]
I have a feeling this might be fonts?

**Comment by BlueJYT** [comment]
It's a bit of a cliche, but clear your cache on that website, and see if that doesn't help.
