### ISSUE TITLE
account logins won't work

### ISSUE THREAD

**Issue by notthecreatoroftaikoforcelv5** [bui/taiko-web#203]
(can't show screenshot now due to me being logged in) (logging out causes the problem below)

So, The first account I made was "90919293" and a password (for this example i'll use "ASDqwe" as the "password")

So I typed in the correct information (in this case 90919293 and password is ASDqwe) but the login system refused to log in and read "invalid username and/or password". This problem is forcing me to make new accounts under the same name and password. Please fix this, I'm tired of making new accounts all the time.

(note for anyone else other than bui who is reading this, ASDqwe isn't my actual password, but 90919293 is my actual username.)

**Comment by bui** [comment]
I had to reset accounts, sorry. Please create a new account.

**Comment by notthecreatoroftaikoforcelv5** [comment]
its ok.
