### ISSUE TITLE
roki lyrics issue

### ISSUE THREAD

**Issue by NekoDekosan** [bui/taiko-web#205]
The song roki has an error in the lyrics, where it should say "selfy" it says "baby" (the word selfie is not spelled wrong, that is how it is in the official lyrics).
![lyricsmistake](https://user-images.githubusercontent.com/54876601/78086240-32903900-7372-11ea-955e-0ca2bca23c2e.jpg)

**Comment by LoveEevee** [comment]
The song however does say "Baby", not "Selfy" in the part where you took the screenshot. The first and third bridge says "Baby", the "Selfy" is in the second bridge, which is not even sung in the short version.
[https://vocaloidlyrics.fandom.com/wiki/ロキ_(Roki)](https://vocaloidlyrics.fandom.com/wiki/%E3%83%AD%E3%82%AD_(Roki))
