### ISSUE TITLE
I forgot my password.

### ISSUE THREAD

**Issue by ghost** [bui/taiko-web#207]
the title is self explanatory. do can you create a "forgot my password" system? or i need to create an new account?

**Comment by shawnshyguy** [comment]
pog

**Comment by LuisSant** [comment]
_**"Kids, i believe this is what you call a pogchamp"**_

**Comment by NoobMan3332** [comment]
hmm...

**Comment by BlueJYT** [comment]
To be honest, this would be a great idea, the only problem with this would be that there would have to be email integration, and depending on how hard that would be to implement in, it could be a while before we see this sort of thing.

Sorry you lost your password dood

**Comment by tiyouo** [comment]
Create new account
