### ISSUE TITLE
Question, how possible would an offline version be?

### ISSUE THREAD

**Issue by LuisSant** [bui/taiko-web#210]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Honestly, Taiko web is THE WAY to play taiko no tatsujin in pc and even mobile, but the downside is that you must be connected to the internet to play. Now playing around with the files that Mozilla Firefox can save using "Save Page As" I tried changing all of the links to files to grab them from my drive instead of the Taiko Web server. Sadly this did not work.

I haven't played around with the files in the git repository, but if we can get a completely offline .HTML then it could be possible to even build a completely functional windows executable and android app out of that. (With enough time of course)

I have no idea of How Taiko Web works. And don't have a lot of knowledge of programming but I mean its fun to experiment.

**Comment by purerosefallen** [comment]
~~You can build a Taiko Web on your own computer~~

**Comment by LuisSant** [comment]
Really? How?

**Comment by bui** [comment]
taiko-web does not require an internet connection when installed, so this is already possible. I'm interpreting this issue as a request for a standalone build.

**Comment by LuisSant** [comment]
Yeah, thats not what i meant... sorry for my stupidity
