### ISSUE TITLE
Suggestion: Preview for Nesin Amatias

### ISSUE THREAD

**Issue by purerosefallen** [bui/taiko-web#218]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Some songs, like Nesin Amatias, its preview differs from the original audio. In this case, the `preview.mp3` should be provided by hand. But the system auto generated for the custom preview of Nesin Aamatias.

Any ways to function Nesin Amatias's preview?

**Comment by bui** [comment]
You can set a custom preview.mp3 manually if you want
