### ISSUE TITLE
Taiko not working

### ISSUE THREAD

**Issue by yawina** [bui/taiko-web#219]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

![Screen Shot 2020-04-29 at 3 08 36 pm](https://user-images.githubusercontent.com/63723174/80562529-5d31e800-8a2b-11ea-89c3-4347b5561a9d.png)
I tried to open taiko web but it just comes up with this page.

**Comment by lonelylittlelucas** [comment]
having same issue, i think it might just be down for maintenance, idk tho

**Comment by josephtian0705** [comment]
I'm having the same issue here....
I want to play it :(

**Comment by gzeok** [comment]
pretty sure that means the edge server cant get a responce from the upstream server. in some cases it can be solved my just refreshing our browser or clearing cache and cookies, but in this case i think it's the site's problem.
