### ISSUE TITLE
Enhancement: Filter screen

### ISSUE THREAD

**Issue by MarNicGit** [bui/taiko-web#221]
# What:

A filter screen that can be triggered from the song select menu. In this screen, it should be possible to set certain filters and then return to the song selection.

# Why: 
This would be super useful for setups with large amounts of songs or for players that only want to play on certain difficulties. Large amounts of songs make browsing a chore and finding the one you want can be a bit hard.

# How:
I suppose it could either be a separate view on its own (like settings) or drawn on top of the song selection. The screen can be triggered either using a hotkey (<kbd>F</kbd>) or a system button.

Possible filters:
* Title
* Subtitle
* Difficulty levels
  * Stars
* TJA or OSU beatmap
* Played or unplayed

Categories don't really need a filter since, well, they're already separated.

**Comment by Glomels** [comment]
Would like to take this if nobody is working on it yet.

**Comment by MarNicGit** [comment]
@Glomels go for it, I haven't been active on this project in forever and afaik nobody else has started on this either

**Comment by KatieFrogs** [comment]
Added in #417
