### ISSUE TITLE
have skills in game

### ISSUE THREAD

**Issue by happygamer-pro** [bui/taiko-web#222]
I have played the game and i realised it didn't have skills.

**Comment by bui** [comment]
Are you referring to Performance Skills from the Switch game?

**Comment by happygamer-pro** [comment]
Yes.

**Comment by happygamer-pro** [comment]
No like the arcade with the skills.

**Comment by bui** [comment]
There's no "skills" in the arcade game. Please clarify your request.

**Comment by happygamer-pro** [comment]
Ok .Just like the switch.

**Comment by bui** [comment]
We will not be implementing performance skills, sorry.

**Comment by happygamer-pro** [comment]
Why?

**Comment by happygamer-pro** [comment]
Why?
