### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by hoqueenieho** [bui/taiko-web#239]
No sound using Chrome and Safari browser in my iphone but it’s working using laptop computer.  May i know how to adjust sound in the browser using mobile?

**Comment by agneskoo** [comment]
Me too. Suddenly no sound in mobile version but still work in Mac version.

**Comment by samsonllam** [comment]
It seems the server has some errors to send the preview.mp3 file

![image](https://user-images.githubusercontent.com/17029792/90677153-88b53880-e28f-11ea-8d5b-921203bc094f.png)
![image](https://user-images.githubusercontent.com/17029792/90677229-a08cbc80-e28f-11ea-906f-9acbc2b20fb3.png)

**Comment by Animenosekai** [comment]
Did you guys check your "Silent Mode" (the thing which you can enable and disable on the left) because it also makes the game silent.

**Comment by samsonllam** [comment]
I think the issue is already been resolved in the few previous update. thankss
