### ISSUE TITLE
Cannot play any songs

### ISSUE THREAD

**Issue by notthecreatoroftaikoforcelv5** [bui/taiko-web#241]
So, I went to Taiko web as I usually do, and the icon (usually don) was replaced by the default icon for a webpage (globe) When I tried to play something, the preview wouldn't load. Then I tried to play the actual song. It exited the loading screen with this error (in the screenshot)
![image](https://user-images.githubusercontent.com/43831177/84594718-333d5500-ae22-11ea-986f-3925a53463ba.png)

**Comment by notthecreatoroftaikoforcelv5** [comment]
Yes, I did try refreshing, the problem persisted. Heres the error log if you're intrested (Prepare for a lot of text)

ks1.kiremani.net/taiko/assets-200222-p3/img/favicon.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/preview.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/main.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
taiko.bui.pm/:1 Uncaught (in promise) Array(2)
ks1.kiremani.net/taiko/songs/26/preview.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/main.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
taiko.bui.pm/:1 Uncaught (in promise) Array(2)
ks1.kiremani.net/taiko/songs/26/main.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/assets-200222-p3/song_skins/bg_don_miku_a.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/oni.osu:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/assets-200222-p3/song_skins/bg_don_miku_b.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/main.vtt:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/assets-200222-p3/song_skins/bg_song_miku.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/preview.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
ks1.kiremani.net/taiko/songs/26/main.mp3:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
taiko.bui.pm/:1 Uncaught (in promise) Array(2)

**Comment by notthecreatoroftaikoforcelv5** [comment]
Senbonzakura loaded preview though

**Comment by notthecreatoroftaikoforcelv5** [comment]
![image](https://user-images.githubusercontent.com/43831177/84597003-e449ec80-ae2e-11ea-85d7-6deddd2d863b.png)

**Comment by bui** [comment]
fixed

**Comment by notthecreatoroftaikoforcelv5** [comment]
thank you!
