### ISSUE TITLE
the bug that i've mentioned before

### ISSUE THREAD

**Issue by LuisFellp** [bui/taiko-web#243]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

#236 happened again and its getting worst. 
i have recorded a video: https://youtu.be/kHHeoAvjySs
i was using a keyboard, but it happens using touchscreen too. 

i don't know if is possible to gather logs using phone browser. i love the site, pleass fix it

**Comment by oofyXD** [comment]
i sorta have the same bug, but im not shure so if you have a computer its the better idea
