### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by notthecreatoroftaikoforcelv5** [bui/taiko-web#245]
I'm getting tired of posting these.
![image](https://user-images.githubusercontent.com/43831177/85059724-1bdbd000-b172-11ea-8a8e-fd575585101f.png)

**Comment by notthecreatoroftaikoforcelv5** [comment]
![image](https://user-images.githubusercontent.com/43831177/85059787-3746db00-b172-11ea-9e72-d05e471a7a63.png)
another photo with error log

**Comment by bui** [comment]
The site loads fine for me.

You have a habit of reporting intermittent site issues the moment they occur, which while I appreciate, this issue tracker is not suited for. In the future, please report any long-lasting server issues directly to me at taiko@bui.pm.
