### ISSUE TITLE
Stuck on 39% "An error occurred, please refresh"

### ISSUE THREAD

**Issue by saulami** [bui/taiko-web#250]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

The loading screen is stuck on 39% and it comes up with the message telling you to refresh. Once you refresh it still does not work. I've tried it on multiple devices too. 

![unknown (12)](https://user-images.githubusercontent.com/68166243/87233259-ba4c0180-c3bd-11ea-9ddc-699c01af670d.png)

![unknown (11)](https://user-images.githubusercontent.com/68166243/87233234-98eb1580-c3bd-11ea-8d21-f9925b61f3e2.png)

**Comment by gzeok** [comment]
same happening on phone for me

![9660CE1A-64B4-4CDC-A6C2-619674E0E9F2](https://user-images.githubusercontent.com/64531852/87233421-43176d00-c3bf-11ea-8667-fed891cb6949.png)

**Comment by bui** [comment]
Fixed
