### ISSUE TITLE
The setting of fps

### ISSUE THREAD

**Issue by justonlyplayer** [bui/taiko-web#267]
I hope you can add setting of fps like 30 fps/ 60 fps to player. When I play it fps is drop so much.

**Comment by BlueJYT** [comment]
Well, it's not like the game is trying to drop FPS. This simulator does take a bit of processing to get a good framerate. You might want to close your other tabs, and you might want to play on a better device depending on what your specs are. A good tip is to decrease the quality settings by going into Game Settings. Other than that, just make sure that your computer isn't the problem.
