### ISSUE TITLE
Doesn't work in Chromium

### ISSUE THREAD

**Issue by ThatOneCalculator** [bui/taiko-web#269]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Game works fine in Firefox and Chrome, but Chromium browser doesn't work. Pop!_OS 20.04 LTS

Error from Chromium when trying to load:

```
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_sanka.wav
EncodingError: Unable to decode audio data,https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_sanka.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/neiro_1_ka.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/se_jump.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/se_balloon.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_songsel.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_start.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_results.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/neiro_1_don.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_fullcombo.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_renda.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_results_fullcombo.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_results_fullcombo2.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_diffsel.wav
EncodingError: Unable to decode audio data: https://ks1.kiremani.net/taiko/assets-200222-p3/audio/v_title.wav
Percentage: 72%
```

**Comment by LoveEevee** [comment]
Chromium installed with a package manager gives the error, but the official Chromium build from [download-chromium.appspot.com](https://download-chromium.appspot.com/) works fine. Please report this issue to [package maintainers](https://launchpad.net/ubuntu/+source/chromium-browser/+bugs) not here.

**Comment by ThatOneCalculator** [comment]
> Chromium installed with a package manager gives the error, but the official Chromium build from [download-chromium.appspot.com](https://download-chromium.appspot.com/) works fine. Please report this issue to [package maintainers](https://launchpad.net/ubuntu/+source/chromium-browser/+bugs) not here.

That's super weird. You're right, it totally works in the downloaded version. Thank you!

**Comment by ThatOneCalculator** [comment]
Also, turns out installing from the dev ppa with apt works fine. Very odd. Thank you nonetheless!
