### ISSUE TITLE
Mobile is barely playable

### ISSUE THREAD

**Issue by Pursuit-W** [bui/taiko-web#274]
If you’re playing a really hard song and you get a wave of notes, at some point, you’ll get misses, even though you’re hitting the notes correctly

**Comment by Pursuit-W** [comment]
Example: playing behemoth, playing the moment near the end on mobile is impossible cuz of sudden misses

**Comment by Animenosekai** [comment]
Same problem here, seems to be happening because of a lack of touch detection when two notes are close (especially when you are hitting fast with one finger and trying to hit notes with the other finger)

**Comment by Franuwu-potato** [comment]
Me too :p
