### ISSUE TITLE
Timing suddenly changes in Red Rose Evangel

### ISSUE THREAD

**Issue by Pursuit-W** [bui/taiko-web#275]
the timing goes more and more off as the songs goes since the beginning

**Comment by LoveEevee** [comment]
There has been a fix to Ai want U chart in #294 which might fix your issue, though I could not reproduce your problem even before that using [the TJA from e2339999](https://wikiwiki.jp/tja292/%E8%AD%9C%E9%9D%A2%E4%B8%80%E8%A6%A7/%E6%9C%AC%E5%AE%B6%E8%AD%9C%E9%9D%A2/wii%E8%B6%85)

**Comment by Pursuit-W** [comment]
> There has been a fix to Ai want U chart in #294 which might fix your issue, though I could not reproduce your problem even before that using [the TJA from e2339999](https://wikiwiki.jp/tja292/%E8%AD%9C%E9%9D%A2%E4%B8%80%E8%A6%A7/%E6%9C%AC%E5%AE%B6%E8%AD%9C%E9%9D%A2/wii%E8%B6%85)

huh, cool, I never felt a problem in Ai want U, but last time I played red rose evangel, the timing felt better than previously, might just be me
