### ISSUE TITLE
Latency calibration fails to load

### ISSUE THREAD

**Issue by HenryLoo** [bui/taiko-web#277]
Selecting the "Latency Calibration" option from the game settings menu leads to an unending load screen.

Console output:
![image](https://user-images.githubusercontent.com/7819192/98485009-51886080-21c8-11eb-941c-6a8372c59b46.png)

**Comment by LoveEevee** [comment]
Fixed in [61c3bb1](https://github.com/bui/taiko-web/commit/61c3bb16375c2eab5f2711d4ad8113ae9b32e9a0)
