### ISSUE TITLE
No audio after replaying custom songs

### ISSUE THREAD

**Issue by varnex** [bui/taiko-web#281]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

After playing a custom .tja all the way to the results screen, selecting the same song will cause no song audio to load. 

The problem is remedied after selecting a different custom .tja.

```
Taiko-Web version: https://github.com/bui/taiko-web/commit/3b1452eb06b5d1bbbec4f1bba0314b8bb8123ddf
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
Screen size: 770x487, outer: 783x606, ratio: 2.00
Blur performance: 3.4ms, all images: 488ms
Page load: 1.8s
Language: en (en-US, en, fr, zh-CN, zh-TW)
Audio Latency: +128ms, Video Latency: 0ms
```

**Comment by LoveEevee** [comment]
Fixed in #294
