### ISSUE TITLE
'blowing balloon' and 'banner on track when song complete' not shown

### ISSUE THREAD

**Issue by kawaiidora** [bui/taiko-web#282]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

1. donchan blowing balloon effect are not shown
expected: (something like this)
![image](https://user-images.githubusercontent.com/41125342/100483066-2a022500-30f0-11eb-9194-d671611b19ae.png)

actual:
![image](https://user-images.githubusercontent.com/41125342/100482488-7a2cb780-30ef-11eb-9ac8-b8de69971fac.png)

2. song complete banner are not shown (it has sound effect only)
expected: (something like this)
![image](https://user-images.githubusercontent.com/41125342/100483322-66358580-30f0-11eb-89b5-21a71c022b32.png)

actual: sound effect only, no image shown

my environment: (using latest Chrome)
```
Taiko-Web version: https://github.com/bui/taiko-web/commit/3b1452eb06b5d1bbbec4f1bba0314b8bb8123ddf
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Screen size: 1920x1080, outer: 1904x1064, ratio: 1.00
Blur performance: 0.8ms, all images: 2ms
Page load: 1.4s
Gamepad #1: Xbox 360 Controller (XInput STANDARD GAMEPAD), buttons: 17, axes: 4
Language: en (en, zh-CN, zh-TW)
Audio Latency: 0ms, Video Latency: 0ms
```

**Comment by bui** [comment]
#167
