### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by CutlerRU** [bui/taiko-web#292]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
When attempting to access the `taiko.bui.pm` address I am greeted by a 500 Internal Server Error :( 

![image](https://user-images.githubusercontent.com/15910085/100918128-17983a80-34a6-11eb-8fdd-12bfcc5c573c.png)

![image](https://user-images.githubusercontent.com/15910085/100918136-19fa9480-34a6-11eb-836c-ec9fe6106b05.png)

**Comment by BlueJYT** [comment]
Having the same exact issue, ~~i did clear cache but i don't know if that does anything lmao~~
