### ISSUE TITLE
Sotsu Omeshiki Full easy, medium, and hard modes have empty tracks

### ISSUE THREAD

**Issue by ElFisho2** [bui/taiko-web#296]
Sotsu Omeshiki Full easy, medium, and hard modes have empty tracks, but the extreme mode is fine
there are no notes for the entire song and in the beginning you hear the 'fail' noise (the sfx played when you finish and do not clear a song)
<img width="1280" alt="Screen Shot 2020-12-07 at 5 15 35 PM" src="https://user-images.githubusercontent.com/75509021/101412422-97f8da00-38b0-11eb-8aad-d484c5c8eb00.png">
<img width="379" alt="Screen Shot 2020-12-07 at 5 15 18 PM" src="https://user-images.githubusercontent.com/75509021/101412432-99c29d80-38b0-11eb-9673-a402ec56f229.png">

here is a video 
[Taiko-web sotsu omeshiki full bug480.zip](https://github.com/bui/taiko-web/files/5655666/Taiko-web.sotsu.omeshiki.full.bug480.zip)

```
Taiko-Web version: https://github.com/bui/taiko-web/commit/665fc57929b48c895f208b497ae71c84cd8cee57
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
Screen size: 1280x606, outer: 1280x717, ratio: 2.00
Blur performance: 3.2ms, all images: 37ms
Page load: 2.0s
Language: en (en-US, en)
Audio Latency: 0ms, Video Latency: 0ms
```

**Comment by Yonokid** [comment]
one sec

**Comment by bui** [comment]
Fixed, though the old chart may still be cached in your browser
