### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by Storm-ctrl** [bui/taiko-web#298]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
My problem's hard to screenshot, as it is a mixture of hardware and software. 

I'm running the sim on Google Chrome 87.0.4280.88 on MacOS 10.15.7 (Catalina). Whenever I play with keyboard, it works as expected. However, whenever I play with my Xbox One Controller, it controls not as well. The left joystick works for navigating menus, but is as useful as a pebble during songs. B works as a kat note, while it is used as a confirm button, and vice versa with the A button. I cannot confirm if the problem persists with other controllers, for I do not own a PS4 or Switch controller.
I suggest implementing a custom bind setup for controllers like the one for keyboards.

**Comment by bui** [comment]
If you enter the settings menu with your controller, you can choose between three controller layouts; the same ones used on console taiko games.

The Xbox B button working as confirm button is intended behavior.
