### ISSUE TITLE
Certification was expired. (SERVERS DOWN)

### ISSUE THREAD

**Issue by qwertyug** [bui/taiko-web#299]
![Screenshot 2020-12-15 at 7 14 37 AM](https://user-images.githubusercontent.com/74257395/102233620-51edd880-3ea5-11eb-8067-02db406fee7a.png)
![Screenshot 2020-12-15 at 7 14 25 AM](https://user-images.githubusercontent.com/74257395/102233626-51edd880-3ea5-11eb-95a4-c59523700268.png)

**Comment by qwertyug** [comment]
UPDATE: seems like servers are down
![Screenshot 2020-12-15 at 7 59 28 AM](https://user-images.githubusercontent.com/74257395/102239314-941a1880-3eab-11eb-80be-790056160b97.png)

**Comment by qwertyug** [comment]
2player is down too

**Comment by qwertyug** [comment]
![image](https://user-images.githubusercontent.com/74257395/102253459-34783900-3ebc-11eb-89e5-36ba31b59f06.png)
![Screenshot 2020-12-15 at 9 58 36 AM](https://user-images.githubusercontent.com/74257395/102253502-3fcb6480-3ebc-11eb-84f9-c8b375b165de.png)
uh oh

**Comment by bui** [comment]
fixed
