### ISSUE TITLE
CORS error: Could not load song SONG (occurs for many songs)

### ISSUE THREAD

**Issue by fossegrim** [bui/taiko-web#300]
![Screenshot from 2020-12-17 21-31-39](https://user-images.githubusercontent.com/24797093/102540448-584fa080-40af-11eb-8c70-c23c91d5e65c.png)

Many songs refuse to play, and outputs an error message as shown, when i try to play them. It happens on most, but not all the songs i try.

**Comment by bui** [comment]
Fixed
