### ISSUE TITLE
Stuck at 99% loading "An error occurred please refresh"

### ISSUE THREAD

**Issue by dfg1801** [bui/taiko-web#301]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

It was originally stuck at the first screenshot at 73%, then I copy/pasted the link in the error into a new tab and refreshed the taiko.bui page. It then went to 99% and I tried the same copy/pasting the link method (in second screenshot) and it said the origin was unreachable. See third screenshot. I tried resetting the router, clearing my cache, restarting my computer. My friend can load the website. I have been able to load it several times before now, idk what changed. 

![Screen Shot 2020-12-17 at 6 31 53 PM](https://user-images.githubusercontent.com/71857817/102575025-4c0b1980-4096-11eb-9686-ae2a5ec3dabc.png)
![Screen Shot 2020-12-17 at 6 49 33 PM](https://user-images.githubusercontent.com/71857817/102576009-a5744800-4098-11eb-8dca-5c9c1d2596f7.png)
![Screen Shot 2020-12-17 at 6 38 55 PM](https://user-images.githubusercontent.com/71857817/102576091-d94f6d80-4098-11eb-9fa6-3a5b4dc08e7b.png)

Thanks for your time :)

**Comment by fossegrim** [comment]
I experiencing this problem today also. Probably related to https://github.com/bui/taiko-web/issues/300.

**Comment by bui** [comment]
Fixed

**Comment by dfg1801** [comment]
Thanks 👍
