### ISSUE TITLE
these stuff and people?

### ISSUE THREAD

**Issue by oofyXD** [bui/taiko-web#308]
![image](https://user-images.githubusercontent.com/76968752/103570716-77f01280-4e7e-11eb-99d8-d8a66c04a15d.png)
![image](https://user-images.githubusercontent.com/76968752/103573639-6a895700-4e83-11eb-9316-7bf8d2152fa2.png)
![image](https://user-images.githubusercontent.com/76968752/103573847-c94ed080-4e83-11eb-8918-782d83bdd010.png)
![image](https://user-images.githubusercontent.com/76968752/103573942-f13e3400-4e83-11eb-8c7c-ab3934b524f0.png)
![image](https://user-images.githubusercontent.com/76968752/103574071-221e6900-4e84-11eb-94f3-5f5631a4f194.png)

multiple things

**Comment by oofyXD** [comment]
might be a little extra, but hey i like taiko no tatsujin

**Comment by bui** [comment]
#167
