### ISSUE TITLE
Error in entering the site (An error occurred, Please refresh)

### ISSUE THREAD

**Issue by CinnaBu** [bui/taiko-web#309]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Hi there sorry for contacting, i am new to your Taiko simulator and i've been having some errors to log in, it stops at 38%, here are some pictures, I don't know if you need all the codes, so i'm gonna put it all in you need it.
![ERROTAIKO1](https://user-images.githubusercontent.com/76978730/103594038-4440d700-4ed6-11eb-9880-96d6cfd73c46.png)
![ERROTAIKO2](https://user-images.githubusercontent.com/76978730/103594054-4dca3f00-4ed6-11eb-850a-771c6a0b9c26.png)
![ERROTAIKO3](https://user-images.githubusercontent.com/76978730/103594059-528ef300-4ed6-11eb-9549-0030d863003a.png)
Again so sorry for contacting about the error, have a great day!

**Comment by bui** [comment]
It looks like you're getting 403 errors connecting to Cloudflare's network. This is not an issue with taiko-web.
