### ISSUE TITLE
Not sure if this is an issue or not, song downloads don't seem to be working.

### ISSUE THREAD

**Issue by haruwawa** [bui/taiko-web#312]
I've tried googling this many times, dropping files and trying many other things. It always says the note charts aren't in the folder. Is this a glitch or am I doing something wrong?

**Comment by LoveEevee** [comment]
You probably need to unzip the files

**Comment by haruwawa** [comment]
> You probably need to unzip the files

Thank you so much! The thing is, some files don't play sound. Is that ok?

**Comment by LoveEevee** [comment]
Check the filenames inside the folders, if they look like this then the sound should work:
![image](https://user-images.githubusercontent.com/23621460/104773540-45032400-5786-11eb-85cc-98c4f8dcff40.png)

However, if they look like this, then you need to delete the files and extract from the zip again, but this time using [sjisunzip](https://github.com/kjerk/sjisunzip/releases/tag/v0.1-alpha):
![image](https://user-images.githubusercontent.com/23621460/104773801-aaefab80-5786-11eb-81b1-878006f4bc36.png)
