### ISSUE TITLE
What does the screen cause?

### ISSUE THREAD

**Issue by XxxFranKTHxxX** [bui/taiko-web#331]
We still don't know What's going on like that?
![Screenshot_1](https://user-images.githubusercontent.com/78913099/107641098-c4144b00-6ca5-11eb-89f9-bcf48bf6c481.png)
![Screenshot_2](https://user-images.githubusercontent.com/78913099/107641106-c5457800-6ca5-11eb-8a7f-cd3bed3e1d71.png)

**Comment by oofyXD** [comment]
is there something wrong with your computer, like is the screen broken?

**Comment by XxxFranKTHxxX** [comment]
Not wrong cuz I'm using Notebook **gaming**

**Comment by mrLoliKing** [comment]
Does the fan of your gpu or cpu is cool enough because when your gpu heat that much it can cause some graphical issues

**Comment by XxxFranKTHxxX** [comment]
ok
