### ISSUE TITLE
Taiko Web consistently has a loading error

### ISSUE THREAD

**Issue by Storm-ctrl** [bui/taiko-web#332]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Imagine this, if you will. I attempt to load up the site in the last 10 minutes of 6th period. It stops and gives an error screen anywhere from 34 to 39%. I'm confused, but I accept it. School internet isn't the best. I go home and try again, on a connection 5 times better. Same issue. So, I give up and do my homework. I repeatedly try to access the site again numerous times over the next two weeks. Same issue appears, time and time again. Eventually, I come to the conclusion that maybe it's my browser (Chrome). So I try on Safari. This time, it pops an error on 0%. So, I go to bed, and file this issue the next morning. 
No, refreshing doesn't work. Clearing my cache doesn't help. Running in a different version of Chrome doesn't help. A second try on Safari produced a 38% error. Running on MacOS.

Error info (Debug):```
NetworkError: A network error occurred.: https://taiko.uk/taiko/assets-201202-p1/fonts/Kozuka.otf
NetworkError: A network error occurred.: https://taiko.uk/taiko/assets-201202-p1/fonts/TnT.ttf
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/vectors.json?1fceaad
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/notes_hit.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/notes.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/title-screen.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/notes_drumroll.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/notes_explosion.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/balloon.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/bg-pattern-1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/difficulty.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_normal_a.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/taiko.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/dancing-don.gif
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_normal_b1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_normal_b2.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_10combo_a.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_gogo_a.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_10combo_b1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_10combo_b2.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_gogo_b1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_gogo_b2.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_gogostart_b2.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_clear_a.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_gogostart_b1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_gogostart_a.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_clear_b1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/don_anim_clear_b2.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/bg_genre_def.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/fire_anim.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/fireworks_anim.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/bg_score_p1.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/bg_score_p2.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/bg_settings.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/bg_pause.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/badge_auto.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/touch_fullscreen.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/touch_pause.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/mimizu.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/results_flowers.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/results_mikoshi.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/results_tetsuohana.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/settings_gamepad.png
Loading error: https://taiko.uk/taiko/assets-201202-p1/img/results_tetsuohana2.png
Percentage: 34%
```
Screenshots:
![Screen Shot 2021-02-12 at 7 02 46 AM](https://user-images.githubusercontent.com/70658343/107771437-5f3a0e80-6d00-11eb-8738-8d9e079b917d.png)
![Screen Shot 2021-02-12 at 7 02 54 AM](https://user-images.githubusercontent.com/70658343/107771451-63fec280-6d00-11eb-9527-191822c499a3.png)

**Comment by BigBellyThomas** [comment]
I sent in a request about the same issue you're on about just not with as much information and not as well crafted as this one. the site just won't load no matter what you try to start it on. pls fix, I'm sure a lot of us are just very bored in school.

**Comment by bui** [comment]
I can't reproduce this issue
