### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by Blucherry** [bui/taiko-web#334]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
The browser is google chrome I am using might be a server issue?
![Capture](https://user-images.githubusercontent.com/79113292/109423804-c6caac00-79d8-11eb-9f77-eb1773f73ad6.PNG)

**Comment by mawakeb** [comment]
yup I have the same issue and this happened 20 days ago too. Last time it got fixed after about 12 hrs, but not sure how long it's going to last this time. If this is not for maintenance or something, please fix it!!

**Comment by Blucherry** [comment]
never mind its back this ticket  is closed
