### ISSUE TITLE
The Ballon note was not able to hit it. Red,Blue and Drumroll (yellow long note) is ok but for all of the song, the Ballon Note is not able to hit it (no reaction when pressed. .

### ISSUE THREAD

**Issue by aaron1132701723** [bui/taiko-web#336]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。

**Comment by aaron1132701723** [comment]
i saw this issue has been raised on #109 , but can anyone teach me how to resolve it from my end?

Thankss

**Comment by bui** [comment]
Balloons work, a counter just has not been implemented yet.
