### ISSUE TITLE
How can I re-calculate my video delay?

### ISSUE THREAD

**Issue by angelcakes12346** [bui/taiko-web#338]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

I accidentaly messed the video delay up and now I have no idea how to fix it. Can anyone help?
![image](https://user-images.githubusercontent.com/81391301/112548799-2d05dd00-8d93-11eb-9cad-3427df63610e.png)

**Comment by Animenosekai** [comment]
Go to the settings, there should be a "Latency" setting were you can change your video delay

**Comment by nxbulae** [comment]
i have the same problem but i cant get back to the settings

**Comment by Animenosekai** [comment]
> i have the same problem but i cant get back to the settings

Why?

**Comment by Animenosekai** [comment]
> i just cant find the button, i think that was the poster's problem too

In the song list, there should be a "song" which name is "Game Settings"

<img width="1337" alt="japanese" src="https://user-images.githubusercontent.com/40539549/116281322-e3d9ec00-a789-11eb-8f31-52ff820e14d4.png">
<img width="1337" alt="english" src="https://user-images.githubusercontent.com/40539549/116281328-e63c4600-a789-11eb-8941-8a454d24a817.png">

Click on it and you should find a category "Latency"

**Comment by nxbulae** [comment]
ok thank you
