### ISSUE TITLE
multi player

### ISSUE THREAD

**Issue by pikoloid** [bui/taiko-web#342]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
WHERE IS MULTIPLAYER. WTH
![Screenshot 2021-04-07 8 58 41 AM](https://user-images.githubusercontent.com/78498387/113870091-77b62a80-977f-11eb-82ca-dd8af1172b6b.png)

**Comment by JackyChiouts** [comment]
I also have this problem too!

**Comment by anim3w33b** [comment]
Please fix this issue :p
