### ISSUE TITLE
No sound in custom song list mode in some cases

### ISSUE THREAD

**Issue by AWTPG** [bui/taiko-web#347]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

when using "custom song list" I uploaded the song file from 太鼓次郎 
on my chromebook it is playable with sound, everything normal.
but same file, same setting, using my Mac the sound of song disappear.
I tried many times, also change the file name but didn't fix.
<img width="1680" alt="螢幕快照 2021-04-14 下午5 47 15" src="https://user-images.githubusercontent.com/82528432/114739803-7f5e6c00-9d49-11eb-8a06-80dc82f5bbdb.png">
```
Taiko-Web version: https://github.com/bui/taiko-web/commit/1fceaadc7d44423f4c4c28cc48b8ab2cf44799b5
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114
Screen size: 1680x916, outer: 1680x1027, ratio: 2.00
Blur performance: 1.7ms, all images: 356ms


Page load: 4.7s
Language: tw (zh-TW, zh, en-US, en)
Audio Latency: 0ms, Video Latency: 0ms
```

**Comment by LoveEevee** [comment]
Look in your song folder and make sure the filenames do not look broken (eg. `ânâbâsü[âVâôâZâTâCâU.ogg` instead of `ハッピーシンセサイザ.ogg`).
Please note that if you change the file name of the files, you will also need to open the .tja file in a text editor and change the text that starts with `WAVE:` to your new file name.

If that is not the issue, then please upload the song that you have problems with.

**Comment by AWTPG** [comment]
> Look in your song folder and make sure the filenames do not look broken (eg. `ânâbâsü[âVâôâZâTâCâU.ogg` instead of `ハッピーシンセサイザ.ogg`).
> Please note that if you change the file name of the files, you will also need to open the .tja file in a text editor and change the text that starts with `WAVE:` to your new file name.
> 
> If that is not the issue, then please upload the song that you have problems with.

I tried and it still didn't work. the file name indeed is broken. I guess Mac is not supporting Japanese character. I want to change the WAVE:  after changed the file name but seems like text editor in Mac does not support UTF-8 (or something I don't really understand, the error window pup up every time when I try to open it)

On the other hand, since my mac didn't support Japanese character, I search a song which is English title and it WORKS! ( I use "Lemon" which is also from 太鼓次郎. So I think the file name is indeed the issue, but I just can't fix it with my build-in editor.

maybe there is a suggested text editor?
thank you, really appreciated!
