### ISSUE TITLE
No sound while playing on iPad any browser

### ISSUE THREAD

**Issue by tyyap9798** [bui/taiko-web#355]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

There is no sound while playing on iPad, but sound works on an android phone and pc. Tried safari, Mozilla Firefox and chrome on iPad but all no sound, please fix thank you.

**Comment by bui** [comment]
What iOS and Safari version are you using?

**Comment by tyyap9798** [comment]
iOS 14.2 but not important I think, 2 of my friend’s iPad also no sound on the website.

**Comment by Animenosekai** [comment]
Did you check if your "Silent Mode" was off (the thing which you can enable and disable on the side)?
