### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Ch4osContr0l** [bui/taiko-web#360]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
Taiko was working fine yesterday but now there is a error 500 whenever i go to open the website
![Screenshot 2021-04-29 7 43 49 AM](https://user-images.githubusercontent.com/40373492/116545719-c195ba80-a8be-11eb-87df-bc8c3dcb5d78.png)

**Comment by Elasder123** [comment]
> ###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
> ###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
> Taiko was working fine yesterday but now there is a error 500 whenever i go to open the website
> ![Screenshot 2021-04-29 7 43 49 AM](https://user-images.githubusercontent.com/40373492/116545719-c195ba80-a8be-11eb-87df-bc8c3dcb5d78.png)

I have the same problem and it seems like people have the same problem then

**Comment by cupofdirtfordinner** [comment]
im pretty sure this is happening on a very large scale bc i also have the same problem atm.
![image](https://user-images.githubusercontent.com/75740323/116553055-539dc300-a8bf-11eb-9420-60f35af5561c.png)

**Comment by silkshrimp** [comment]
This is definitely a large scale problem. It's happening to me too, though I thought Taiko Web was a little off yesterday when it never prompted me to vote for today's new song.
![Screenshot 2021-04-29 at 9 00 44 AM](https://user-images.githubusercontent.com/78034187/116563340-8ea4f400-a8c9-11eb-832f-f574582dbe1f.png)

**Comment by yxkimxrax** [comment]
Same issue here, tried playing at around 8:30 am EST. Currently, I’m still getting the Internal Server Error as well. 
![05D09665-19DC-447E-8F18-82026F4C8A49](https://user-images.githubusercontent.com/77813672/116575169-6672c080-a8dc-11eb-8e4c-b372b336b58a.png)

**Comment by CanIgetaHiya** [comment]
Code List of 500 Internal Server Errors
--
Code | Explanation
500.11 | The application is crashing down on the webserver when a request is made by a user agent.
500.12 | The application is under the restart process on the webserver.
500.13 | The web server is too busy with other requests. In other words, it is overloaded with a large number of requests, which is more than its capacity.
500.14 | Invalid application configuration on the server. The WordPress website installation is incorrect or corrupted.
500.15 | Direct requests for GLOBAL.ASA are not allowed.
500.16 | UNC authorization credentials are incorrect.
500.17 | URL authorization store cannot be found.
500.18 | URL authorization store cannot be opened.
500.19 | Data for this file is configured improperly in the Metabase.
500.2 | URL authorization scope cannot be found.
500.21 | Module not recognized.
500.5 | A rewrite error occurred during RQ_BEGIN_REQUEST notification handling. A configuration or inbound rule execution error occurred.
