### ISSUE TITLE
Internal Server Error + Balloon not working

### ISSUE THREAD

**Issue by Cendrecovfefe** [bui/taiko-web#378]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Hello,

It has already happened in the past, so I guess I don't have much to explain. 500 Internal Server Error
![TAIKOERROR](https://user-images.githubusercontent.com/85977999/122154018-5dc25380-ce64-11eb-9dd4-9d93b7f70677.PNG)

Also the balloon isn't working, is it normal ? 

Thank you.

**Comment by bui** [comment]
Balloon does work, there is just no visual representation
