### ISSUE TITLE
tja+oggファイルをダウンロードできますか？|Can I download the TJA + Ogg file?

### ISSUE THREAD

**Issue by fon11731** [bui/taiko-web#382]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
I want to download the tracks locally and open them with Taigu Jiro.
曲を地元にダウンロードしたいです。太鼓次郎で開けます。

**Comment by bui** [comment]
Possible with plugin
https://github.com/KatieFrogs/taiko-web-plugins/blob/main/download-chart.taikoweb.js
