### ISSUE TITLE
Glitch in custom songs 

### ISSUE THREAD

**Issue by Noah43448** [bui/taiko-web#383]
i can use netplay for custom songs but when i use the option i cant exit out of the "waiting for player screen" and i'd had to close out the whole tab and reopen it again
![Screenshot 2021-08-14 9 13 53 PM](https://user-images.githubusercontent.com/84691255/129463897-f5c28b61-4849-48ba-a127-9514d9f912ec.png)

**Comment by KatieFrogs** [comment]
Fixed in #411
