### ISSUE TITLE
iOS12の「前前前世」に音が出ない

### ISSUE THREAD

**Issue by OhtaniS** [bui/taiko-web#387]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

iOS12の「前前前世」に音が出ない
音が出ない曲もあります
ドラムなし

**Comment by littlekan-gitee** [comment]
Try clearing the browser cache.
ブラウザのキャッシュをクリアしてみます。
试试清除浏览器缓存。
