### ISSUE TITLE
500 internal server

### ISSUE THREAD

**Issue by Neeloz** [bui/taiko-web#391]
This has been going on for a whole day. It has never been this long either. :/
![Screenshot 2021-09-19 12 36 41 AM](https://user-images.githubusercontent.com/90998685/133915645-951b2066-2234-4bea-94c5-2fa1a434c588.png)

**Comment by Chateauvisionn** [comment]
I have this too
![screen0](https://user-images.githubusercontent.com/89737965/133933557-b0d78431-bb81-4b73-8741-d226f68ce316.jpg)
