### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by waki285** [bui/taiko-web#393]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

I having this problem,  
![Internal Server Error](https://user-images.githubusercontent.com/67305123/134616443-17e7a29f-9f27-440f-89df-9aef8d31f020.png)
how to fixed it?

**Comment by olucaslab** [comment]
It is happening here too...

**Comment by Chateauvisionn** [comment]
I have this problem too
