### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by froggiepen** [bui/taiko-web#394]
Wante to play taiko but this showed up ;
![Captura de pantalla (220)](https://user-images.githubusercontent.com/81500443/134718974-9cd36482-8a16-4f03-8a89-7585d7a87adb.png)
;

**Comment by nyzhb000919** [comment]
same problem

**Comment by BurntToast69** [comment]
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

The sever is probably having issues with traffic or general maintenance, it will be down for a while if that is the case. If the sever got overloaded and damaged, they may be replacing the whole thing which can take weeks, if not they are probably just fixing smaller issues or are updating Taiko itself, the only thing you can do is wait, and keep waiting
