### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by MixerBlaze** [bui/taiko-web#398]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
500 Server error for everybody
![servererror](https://user-images.githubusercontent.com/62030864/143374475-0bebd247-96d1-49a5-9024-4d396fc6b966.PNG)
.

**Comment by hajime6174** [comment]
![image](https://user-images.githubusercontent.com/95013690/143389625-770b846e-ec71-4ad1-958c-55c0638d6a75.png)
同問

**Comment by Bambaclad1** [comment]
Same was for me. Isn´t there an way to like archive this whole site to play taiko offline?

**Comment by off-sketch** [comment]
i finally find some osu!taiko files for taikoweb, and now we have this, an error.....SHIT!
![500 Internal Server Error - Google Chrome 25_11_2021 15_17_46](https://user-images.githubusercontent.com/95036973/143457621-bc7a0c14-e6c1-49a1-8f54-53af9a4ddbb5.png)

**Comment by MixerBlaze** [comment]
> Same was for me. Isn´t there an way to like archive this whole site to play taiko offline?

I think so, since it is all downloaded to local client. Although, I don't know what parts to tell chrome to download. If anyone figures this out, that would be nice.

**Comment by MixerBlaze** [comment]
@Bambaclad1 you should also be able to compile the emulator yourself, supposedly.

**Comment by Bambaclad1** [comment]
> @Bambaclad1 you should also be able to compile the emulator yourself, supposedly.

eh, how? i am kinda new into github

**Comment by waki285** [comment]
some

**Comment by MixerBlaze** [comment]
@Bambaclad1 @waki285 I'm not sure. It will require a compiler and Microsoft VSC I think. I don't know much more than that, better to find someone who does know.

**Comment by Ttglitchez** [comment]
![Screenshot 2021-12-14 09 51 46](https://user-images.githubusercontent.com/94857759/146021605-73e54aff-c9c8-4611-ba92-9ccadbdc82c8.png)

**Comment by Slighty4638** [comment]
Internal server error starting since 26 January morning (This screenshot is in the evening
![2022-01-26 (6)](https://user-images.githubusercontent.com/98460115/151152063-fa715ad7-6bcd-4a94-a32f-ff5bd6121e44.png)
)
