### ISSUE TITLE
Songs have different offset

### ISSUE THREAD

**Issue by MyAimHugoFrost** [bui/taiko-web#406]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

I think that songs' offsets either should be perfectly timed-up, or I really want you to add "local offset" so I can personally time-up any song and play it without going to settings every time.
![изображение_2022-01-09_164550](https://user-images.githubusercontent.com/97390537/148682709-0bfbe0bc-f4c6-482a-b47c-eedf51ad55dc.png)

**Comment by KatieFrogs** [comment]
You can temporarily set the offset for a song in the Debug dialog, pause a song and press `Ctrl+Shift+;`
It will get reset after starting another song

**Comment by bui** [comment]
If this is about a default song on taiko.bui.pm, you can let me know about incorrect offsets and I'll fix them
