### ISSUE TITLE
When searching, sprite sheet pops up

### ISSUE THREAD

**Issue by EncryptedUser7** [bui/taiko-web#421]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
When searching in the search bar (specifically "yoru"), the sprite sheet for several assets, including the tabs like "game settings", "search for a song", "custom song list", etc pop up.  (note that I'm playing the japanese version and I translated them myself.)
![image](https://user-images.githubusercontent.com/86505727/156282720-c6f93ab4-048b-466e-b50f-7483411975c0.png)

**Comment by bui** [comment]
You have a plugin enabled that is displaying the canvas cache

**Comment by EncryptedUser7** [comment]
welp, I'm an idiot
