### ISSUE TITLE
Song not synced with the chart

### ISSUE THREAD

**Issue by Syuniikiiss** [bui/taiko-web#428]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

Purple rose fusion is not synced up with the chart. The song doesn't match up at all with the chart anymore like it used to. I don't know if there is any similar problems with any other song but that's what I have found so far.

**Comment by bui** [comment]
Please report issues with ESE songs to the TJADB discord server: https://discord.gg/XHcVYKW
