### ISSUE TITLE
部分歌曲的音符不對

### ISSUE THREAD

**Issue by Blinhy0131** [bui/taiko-web#430]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
目前已發現歌曲音符不對的
森林裡的熊先生
玩具兵恰恰恰

**Comment by bui** [comment]
Please report issues with ESE songs to the TJADB discord server: https://discord.gg/XHcVYKW
