### ISSUE TITLE
Safariで開けない

### ISSUE THREAD

**Issue by keituuwarireki** [bui/taiko-web#453]
![7FD30DAA-8B03-43BB-AF77-22DF47B18557](https://user-images.githubusercontent.com/101809291/158810419-7e9ae79a-2640-45ed-87c7-d41bde435210.png)

**Comment by keituuwarireki** [comment]
よろしくお願いします

**Comment by keituuwarireki** [comment]
何度読み込みしてもこの画面が出てきます。

**Comment by bui** [comment]
「Debug」をタップしてエラーメッセージを入力してください

**Comment by snowccat** [comment]
```
/api/categories (500): /api/categories
Percentage: 74%
```
same question

**Comment by kouhe3** [comment]
```
/api/categories (500): /api/categories
Percentage: 74%
```

<html>
<body>


Google Chrome | 100.0.4896.46  beta
-- | --



</body>
</html>
