### ISSUE TITLE
BUG. cannot hear music

### ISSUE THREAD

**Issue by ailhayasa** [bui/taiko-web#466]
my default plugin setting is karaoke mode on, but when i turn of that plug in i cant hear music. Only can hear voice of singer. And that's only at creative music.

**Comment by mawakeb** [comment]
I have the same bug but in the official song list only. And the karaoke mode definitely should not be on by default, I was genuinely lost until I found this post

**Comment by AAAAAAAAABbAAABAAAABAA** [comment]
多分エイプリルフールだと思うのですが…。
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈I think it's April Fool's Day ...

**Comment by Kire0** [comment]
> 多分エイプリルフールだと思うのですが…。 ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈I think it's April Fool's Day ...

this could be true. the song of today doesn't even have notes to play.
