### ISSUE TITLE
Can't hear the lyrics.

### ISSUE THREAD

**Issue by foofdoof99** [bui/taiko-web#468]
﻿
I don't know how long this has been happening because I play this game in a public setting and have no headphones. I can't hear the lyrics to ANY song; I looked around in the settings and plugins and saw "karaoke mode" so i tried that, and when I did I could only hear the lyrics and not any of the instruments. Does anyone know what's going on? Is it just me or no?

**Comment by SuperCutie14** [comment]
I think I know why. Today's April Fools Day, and they're doing this as a prank.

**Comment by hayukimori** [comment]
_makes sense_

**Comment by foofdoof99** [comment]
Ohhhhhhhhhhhhhhhhhh
