### ISSUE TITLE
privacy error

### ISSUE THREAD

**Issue by juuked** [bui/taiko-web#563]
Hello. there is an privacy error and the certificate is no longer valid. Is this only happening to me or everyone?
![image](https://user-images.githubusercontent.com/118316029/206748230-63b6a9a3-83b0-4baf-9bed-c9cfeb9fb158.png)
![image](https://user-images.githubusercontent.com/118316029/206748372-1ac4ff39-e7c1-4ba1-8a29-041edcfb2f94.png)

**Comment by bui** [comment]
fixed!
